spring:
  application:
    name: eCommerce
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: db_ser
    password: 123456789
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8000