version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=123456789
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=123456789
    volumes:
      - ./docker-data/mysql:/var/lib/mysql